version: '3.4'

services:
  dockerdemo:
    image: ${DOCKER_REGISTRY-}dockerdemo
    build:
      context: .
      dockerfile: DockerDemo/Dockerfile

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
        - "5672:5672"    # RabbitMQ default port
        - "15672:15672"  # RabbitMQ management console port
    environment:
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

